# Generated by Django 3.2.7 on 2021-09-29 15:47

from django.db import migrations, models
import example.demo.models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20160801_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('project', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(storage=example.demo.models.OverwriteStorage(), upload_to=example.demo.models.FilesModel.upload_path_handler, validators=[example.demo.models.FilesModel.validate_file_type])),
                ('version', models.CharField(max_length=15, validators=[example.demo.models.FilesModel.validate_version])),
                ('compatible', multiselectfield.db.fields.MultiSelectField(choices=[('1.1.9.30', '1.1.9.30'), ('2.0.2.51', '2.0.2.51'), ('2.0.4.14', '2.0.4.14'), ('2.0.5.6', '2.0.5.6'), ('2.1.0.11', '2.1.0.11'), ('2.1.1.12', '2.1.1.12'), ('2.1.1.23', '2.1.1.23'), ('2.1.1.24', '2.1.1.24'), ('2.1.1.26', '2.1.1.26'), ('2.1.2.3', '2.1.2.3'), ('2.1.3.3', '2.1.3.3'), ('2.1.3.5', '2.1.3.5'), ('2.1.3.7', '2.1.3.7'), ('2.1.4.13', '2.1.4.13'), ('2.1.4.14', '2.1.4.14'), ('2.1.4.15', '2.1.4.15'), ('2.2.0.29', '2.2.0.29'), ('2.2.1.18', '2.2.1.18'), ('2.2.1.19', '2.2.1.19'), ('3.0.0.5', '3.0.0.5'), ('3.0.0.8', '3.0.0.8'), ('3.0.0.11', '3.0.0.11'), ('3.0.1.11', '3.0.1.11'), ('3.0.1.14', '3.0.1.14'), ('3.0.2.8', '3.0.2.8'), ('3.0.3.8', '3.0.3.8'), ('3.0.3.9', '3.0.3.9'), ('3.0.3.10', '3.0.3.10'), ('3.1.0.11', '3.1.0.11'), ('3.2.0.12', '3.2.0.12'), ('3.2.0.14', '3.2.0.14'), ('3.2.1.19', '3.2.1.19'), ('3.2.1.20', '3.2.1.20'), ('3.3.0.14', '3.3.0.14'), ('3.3.0.16', '3.3.0.16'), ('3.4.0.22', '3.4.0.22'), ('3.4.0.24', '3.4.0.24'), ('4.0.1.45', '4.0.1.45'), ('4.0.1.48', '4.0.1.48'), ('4.1.0.24', '4.1.0.24'), ('4.2.0.19', '4.2.0.19'), ('4.2.0.21', '4.2.0.21')], default='2.1.1.24', max_length=255)),
                ('activations', models.PositiveIntegerField(blank=True, default=0)),
                ('changelog', models.CharField(blank=True, max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=4096)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, unique=True, validators=[example.demo.models.ProjectsModel.validate_name])),
                ('display_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('homescreen', 'Homescreen'), ('browser', 'Browser'), ('camera', 'Camera'), ('calendar', 'Calendar'), ('clock', 'Clock'), ('contacts', 'Contacts'), ('email', 'Email'), ('gallery', 'Gallery'), ('homescreen', 'Homescreen'), ('media', 'Media'), ('messages', 'Messages'), ('phone', 'Phone'), ('silica', 'Silica'), ('settings', 'Settings'), ('keyboard', 'Keyboard'), ('other', 'Others')], default='other', max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('rating', models.IntegerField(blank=True, default=0)),
                ('total_activations', models.PositiveIntegerField(blank=True, default=0)),
                ('discussion', models.CharField(blank=True, max_length=255)),
                ('donations', models.CharField(blank=True, max_length=255)),
                ('sources', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenshotsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.FileField(blank=True, storage=example.demo.models.OverwriteStorage(), upload_to=example.demo.models.ScreenshotsModel.upload_screenshot_handler, validators=[example.demo.models.ScreenshotsModel.validate_content_type])),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('project', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
