# Generated by Django 3.2.7 on 2021-09-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20210929_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesmodel',
            name='bitness',
            field=models.CharField(blank=True, choices=[(None, 'Any'), ('32', '32-bit only'), ('64', '64 bit only'), ('96', 'Separate 32 and 64 bit patches')], max_length=2),
        ),
    ]
